version: "3.4"
services:
  pathfinder.public.dappnode.eth:
    build:
      context: build/.
      args:
        UPSTREAM_VERSION: v0.1.10-alpha
    image: "pathfinder.public.dappnode.eth:0.4.0"
    ports:
      - "9545:9545"
    environment:
      RUST_LOG: info
      PATHFINDER_ETHEREUM_API_URL: "http://geth.dappnode:8545"
      PATHFINDER_HTTP_RPC_ADDRESS: "0.0.0.0:9545"
    volumes:
      - "pathfinder_data:/usr/share/pathfinder/data"
    restart: unless-stopped
volumes:
  pathfinder_data: {}
